[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-mmacosx-version-min=10.15",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-mmacosx-version-min=11.0",
]

[env]
# Force static linking of lzma on macOS
LZMA_API_STATIC = "1"